allRecipies = [
    {
        "recipie_id": 101,
        "recipie_name": "French Fries",
        "recipie_img": "https://imgs.search.brave.com/HEuzOk0_S65ykV4YRCfSRNwRhw_Djf7VQgoDwCoxRwk/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTU3/MzEyMDcyL3Bob3Rv/L2Jhc2tldC1vZi1m/cmVuY2gtZnJpZXMu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PTdST2ZsWGJEUGpX/UWJVVE1BVGE5MGFs/SVdEaXI2RWFGQnFy/bU1FdVkyeVU9",
        "recipie_method": "Ingredients:\n- 2½ pounds (1.13kg) Yukon gold potatoes, scrubbed, dried, sides squared off, and cut lengthwise into ¼-inch by ¼-inch batons.\n- 6 cups (1.3L) peanut oil.\n\nInstructions:\n- Combine the potatoes and the oil in a large Dutch oven or heavy-bottomed pot. Cook over high heat until oil has reached a rolling boil, about 5 minutes. Continue to cook, without stirring, until potatoes are limp but exteriors are beginning to firm, about 15 minutes. Meanwhile, line a baking sheet with a double layer of paper towels.\n- Using tongs, stir potatoes, gently scraping up any that stick, and continue to cook, stirring occasionally, until golden and crisp, 5 to 10 minutes longer. Using a skimmer or slotted spoon, transfer fries to a paper towel-lined baking sheet. Season with salt (and pepper, if desired) and serve immediately.\n- Note: Do not use sweet potatoes or russet potatoes; the starch content won't hold up to frying in this manner."
    },
    {
        "recipie_id": 102,
        "recipie_name": "Spaghetti",
        "recipie_img": "https://img.freepik.com/free-photo/freshly-cooked-gourmet-pasta-with-healthy-vegetables-generated-by-ai_188544-24689.jpg?t=st=1702294393~exp=1702297993~hmac=d5484c8f7214ba13123c20bbcf843d25273edd6419e8ebd2a2d63e77e6908af7&w=1380",
        "recipie_method": "Ingredients:\n- Regular or whole wheat spaghetti.\n- Extra virgin olive oil.\n- Garlic.\n- Fresh or dried chili flakes.\n- Salt.\n- Parmesan cheese (optional).\n- Parsley (optional).\n\nInstructions:\n- Cook your spaghetti until al dente.\n- Meantime, fry gently garlic and chili in olive oil.\n- Drain spaghetti, reserve 1/2 cup cooking water.\n- Add spaghetti and parley to the skillet.\n- Add as much cooking water as needed to make the pasta moist.\n- Stir well to coat.\n- If you don’t keep it vegan, serve with parmesan cheese.\n- Sprinkle extra chili flakes and parsley, if you like. Enjoy!"
    },
    {
        "recipie_id": 103,
        "recipie_name": "Chola",
        "recipie_img": "https://imgs.search.brave.com/NDb_Xx-pQy6ZNoADPTev4-q2ZhQE0ivKyMZ_YeisHGc/rs:fit:500:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA1Lzg0LzM3Lzky/LzM2MF9GXzU4NDM3/OTI3MV9kcjk4dnhD/UHhsQjhGYjlTZ3lv/UXlicmdpTldGa3FB/Uy5qcGc",
        "recipie_method": "Ingredients:\n- 1 large red onion; plus more thinly sliced for serving (optional)\n- 2 plum tomatoes\n- 2 15-oz. cans chickpeas (do not drain)\n- 3 Tbsp. vegetable oil\n- 1 tsp. cumin seeds\n- 6 garlic cloves, finely grated\n- 1 1\" piece ginger, peeled, finely grated\n- 2 tsp. garam masala\n- 2 tsp. Diamond Crystal or 1¼ tsp. Morton kosher salt\n- 1 tsp. ground coriander\n- ½ tsp. amchur (dry mango powder)\n- ½ tsp. ground turmeric\n- ½ tsp. Kashmiri or other red chile powder\n- ⅛ tsp. ground cinnamon\n- Juice of ½ lime\n- ¼ cup chopped cilantro, plus leaves with tender stems for serving\n- 2 Tbsp. unsalted butter (optional)\n- Steamed rice, naan, or crusty bread (for serving)\n\nInstructions:\n- Grate 1 large red onion on the large holes of a box grater; set aside. Cut ends off 2 plum tomatoes and grate flesh down to skins; discard skins. Set aside separately.\n- Bring two 15-oz. cans chickpeas with their liquid to a boil in a medium saucepan; cook, stirring occasionally, until chickpeas swell slightly and are a bit lighter in color, 10–15 minutes. Remove from heat.\n- Meanwhile, heat 3 Tbsp. vegetable oil in a large skillet over medium. Cook 1 tsp. cumin seeds, swirling pan, until seeds start to pop and sputter, 10–20 seconds. Add 6 garlic cloves, finely grated, one 1\" piece ginger, peeled, finely grated, and reserved grated red onion. Cook, stirring often, until most of the water has evaporated, 7–9 minutes.\n- Add reserved grated tomatoes to skillet and cook, stirring, 1 minute. Add 2 tsp. garam masala, 2 tsp. Diamond Crystal or 1¼ tsp. Morton kosher salt, 1 tsp. ground coriander, ½ tsp. amchur (dry mango powder), ½ tsp. ground turmeric, ½ tsp. Kashmiri or other red chile powder, and ⅛ tsp. ground cinnamon. Cook, stirring, until fragrant and color deepens slightly, about 2 minutes.\n- Add chickpeas with their liquid to pan, reduce heat, and simmer, stirring often, until mixture thickens and takes on a slightly shiny appearance as the oils start to separate, 10–15 minutes. Stir juice of ½ lime, ¼ cup chopped cilantro, and 2 Tbsp. unsalted butter (if using) into chana masala.\n- Divide chana masala among bowls and top with cilantro leaves with tender stems and sliced red onion (if using). Serve with steamed rice, naan, or crusty bread."    },
    {
        "recipie_id": 104,
        "recipie_name": "Cheese Garlic Sandwich",
        "recipie_img": "https://www.simplyrecipes.com/thmb/_P0GaQl_hP8IkClQER1XFiVg3cY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2006__09__Garlic-Bread-METHOD-2-bec7227928124a569a64dc7d0a85f3c1.jpg",
        "recipie_method": "Ingredients:\n- 1 16-ounce (450 g) loaf Italian bread or French bread.\n- 1/2 cup (1 stick, 112 g) unsalted butter, softened.\n- 2 large cloves garlic, smashed and minced.\n- 1 heaping tablespoon chopped fresh parsley.\n- 1/4 cup (25 g) freshly grated Parmesan cheese (optional).\n\nInstructions:\n- Preheat oven to 350°F.\n- Prepare the garlic bread: Cut the loaf in half, horizontally. Mix the butter, garlic, and parsley together in a small bowl. Spread the butter mixture over the two bread halves.\n- Heat in the oven for 10 minutes: Place on a sturdy baking pan (one that can handle high temperatures, not a cookie sheet) and heat in a 350°F (175°C) oven for 10 minutes.\n- Sprinkle with Parmesan (optional) and broil: Remove the pan from the oven. Sprinkle Parmesan cheese over bread if you want. Return to the oven on the highest rack. Broil on high heat for 2 to 3 minutes until the edges of the bread begin to toast, and the cheese (if you are using cheese) bubbles. Watch very carefully while broiling. The bread can easily go from un-toasted to burnt.\n- Slice: Remove from the oven, let cool a minute. Remove from the pan and use a bread knife to cut into 1-inch thick slices. Serve immediately."
    },
    {
        "recipie_id": 105,
        "recipie_name": "Vanilla Pudding",
        "recipie_img": "https://img.freepik.com/free-photo/front-view-delicious-creamy-dessert-with-fresh-strawberries-light-white-wall-dessert-ice-cream-sweet-fruit-taste_140725-52936.jpg?size=626&ext=jpg&ga=GA1.1.341020802.1702211776&semt=ais",
        "recipie_method": "Ingredients:\n- 1 cup (200 g) granulated sugar.\n- ¾ cup (96 g) cornstarch.\n- ¾ cup (96 g) nonfat dry milk powder.\n- 1 teaspoon kosher salt.\n- 2 whole vanilla beans.\n\nInstructions:\n- In a medium bowl, whisk together the sugar, cornstarch, milk powder, and salt; set aside.\n- Split open the vanilla beans and use the back of a knife to scrape out the seeds. Add the seeds to the sugar mixture, and again whisk well to evenly combine, using a fork or the back of the spoon to break up any chunks of vanilla bean seeds. Cut the empty vanilla bean pods into two or three pieces each.\n- Place the vanilla bean pieces into an airtight container or jar, and add the sugar mixture. Seal it, and then give it a few good shakes to distribute the vanilla bean pieces evenly. Store in a cool, dry place.\n- To make pudding: Combine 2 cups of milk with ½ cup of the instant pudding mix in a medium saucepan over high heat, whisking constantly. Bring to a boil, and then immediately reduce the heat to a simmer and continue whisking until the mixture thickens and coats the back of a spoon (about 3 to 5 minutes). Let sit for at least 5 minutes before serving. Store leftovers in an airtight container in the refrigerator."
    },
    {
        "recipie_id": 106,
        "recipie_name": "Paneer",
        "recipie_img": "https://imgs.search.brave.com/4kP_A93m7HibIki33GR3brN5E5I81xoAc1wJeKrwZLc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/cHJlbWl1bS1waG90/by9zaGFoaS1wYW5l/ZXItaW5kaWFuLW1h/aW4tY291cnNlXzk4/NTI3Ni0zMjguanBn/P3NpemU9NjI2JmV4/dD1qcGc",
        "recipie_method": "Ingredients:\n- 3 cups paneer (cottage cheese) cubes\n- 3 whole dry Kashmiri red chillies, broken into pieces\n- 1 tbsp coriander (dhania) seeds\n- 2 tbsp oil\n- 1 tsp cumin seeds (jeera)\n- 1 cup coloured capsicum strips\n- 1 1/2 cups chopped tomatoes\n- Salt to taste\n\nInstructions:\n- To make quick paneer sabzi, combine the red chillies and coriander seeds in a small broad non-stick pan and dry roast on a slow flame for 1 minute. Keep aside to cool slightly.\n- Blend in a mixer to a smooth fine powder and keep aside.\n- Heat the oil in a non-stick kadhai and add the cumin seeds.\n- When the seeds crackle, add the capsicum strips and sauté on a medium flame for 1 to 2 minutes.\n- Add the prepared masala and saute for a minute.\n- Add the tomatoes, salt, and 4 tbsp of water, mix well and cook on medium flame for 5 minutes, stirring occasionally.\n- Add the paneer, mix gently and cook on medium flame for another 1 to 2 minutes, stirring occasionally.\n- Serve the quick paneer sabzi hot."
    },    
    {
        "recipie_id": 107,
        "recipie_name": "Pasta",
        "recipie_img": "https://imgs.search.brave.com/grvpETL_CZo8tLwj51-zeguWlwLTXblmoy9oZZ2rWw0/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDgy/OTY0NTQ1L3Bob3Rv/L2FycmFiaWF0YS1w/YXN0YS5qcGc_cz02/MTJ4NjEyJnc9MCZr/PTIwJmM9LVBHVTNn/aWxuQUVxMUVjY1dY/emRJdkcxOHk5THN2/ZWdVWDZnZ3Q5Tms3/dz0",
        "recipie_method": "Ingredients:\n- 8 ounces dry pasta*, gluten-free or regular\n- 8 ounces grape or cherry tomatoes, cut in half\n- 2 garlic cloves, minced\n- 1/2 yellow onion, thinly sliced\n- 1 small zucchini, chopped and quartered\n- 3 oz cremini mushrooms, sliced\n- 1/2 teaspoon red pepper flakes (optional)\n- 1/2 teaspoon kosher salt\n- 1 1/4 cup pasta sauce of choice\n- 2 1/2 cups water\n- 3 ounces fresh spinach\n\nInstructions:\n- Add the uncooked pasta to a large pot (or pan with deep sides). Add the remaining ingredients – except for the spinach – and mix well. Bring the pot to a boil over high heat.\n- Once boiling, reduce the heat to medium-low and cook the pasta for 10-14 minutes, until al-dente. Stir the mixture every 2 minutes to prevent anything from sticking to the bottom of the pan. (Note: cooking times will vary based on the type of pasta used. I suggest you start to check for doneness based on the minimum cook time on the package instructions)\n- Turn the heat off and fold the spinach into the pasta. Once the spinach has wilted, divide the pasta into serving bowls and top as desired. This recipe is best enjoyed fresh, but leftovers will keep in the fridge for up to 5 days."
    },    
    {
        "recipie_id": 108,
        "recipie_name": "Chilli Paneer",
        "recipie_img": "https://imgs.search.brave.com/ui_ZJ_V4YbJeCJ-SBMppiUxYLeTyQWC9q4qK5I6CqK8/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9teWZv/b2RzdG9yeS5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjEv/MDYvQ2hpbGxpLVBh/bmVlci0xLTEwNjd4/NjE3LmpwZw",
        "recipie_method": "Ingredients:\n- 200 grams Paneer cut into cubes\n- 2 tablespoons Cornflour\n- 1 teaspoon Kashmiri Chilli Powder\n- ½ teaspoon Salt\n- A splash of water\n- Oil for Frying (approximately half cup)\n\nSauce Mixture:\n- 1 tablespoon Soy Sauce\n- 2 teaspoons Red Chilli Sauce\n- 1 tablespoon Ketchup\n- ¼ teaspoon Kashmiri Chilli Powder or paprika\n- ½ teaspoon Vinegar\n- ¼ teaspoon Salt\n- ½ teaspoon Cornflour\n- ½ cup Water\n\nFor the Stir Fry:\n- 2 teaspoons chopped Ginger\n- 2 teaspoons chopped Garlic\n- 2-3 Green Chillies slit lengthwise\n- 2 Onions cubed\n- 1 Capsicum cubed\n- 1 tablespoon chopped Spring Onions\n\nInstructions:\n- Add cornflour, Kashmiri chilli powder, and salt to a bowl; whisk. Add paneer cubes and toss to coat. Sprinkle a little water to help the coating stick to the paneer. Toss and set aside.\n- Heat oil in a wok or pan. Fry paneer on high heat until golden brown. Remove and set aside.\n- Whisk together all the sauce ingredients; set aside.\n- Remove excess oil, leaving 1.5 tablespoons. Add ginger, garlic, and green chillies. Saute, then add onions and capsicum.\n- Stir-fry for 2-3 minutes, then add the paneer cubes. Toss for a minute.\n- Whisk the sauce and add it to the wok. Toss on high heat for 2 minutes until the sauce thickens and coats the paneer.\n- Add a little water if more sauce is desired. Sprinkle with chopped spring onions and serve hot."
    },    
    {
        "recipie_id": 109,
        "recipie_name": "Aloo Paratha",
        "recipie_img": "https://imgs.search.brave.com/0BBnNjiXGRRoDsMxm6oCe3fyO51TeqIi_sTBwC_nVdo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvOTA4/NjQ3ODEyL3Bob3Rv/L3BhcmF0aGEtYW5k/LWN1cmQuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPWptNlVW/WVJHM2dSZjN1ZjY0/eTVBUFh5T25jTlhh/aDA3SktwT2R5cjRo/S3M9",
        "recipie_method": "Ingredients:\nFor Aloo Paratha Dough:\n- 2 1/4 cups whole wheat flour (gehun ka atta)\n- 2 tbsp melted ghee\n- Salt to taste\n\nFor Aloo Paratha Stuffing:\n- 2 1/2 cups boiled, peeled, and mashed potatoes\n- 2 tsp melted ghee\n- 1 tsp cumin seeds (jeera)\n- 1/2 cup finely chopped onions\n- 1 tbsp finely chopped green chillies\n- Salt to taste\n- 1/2 tsp chilli powder\n- 2 tbsp finely chopped coriander (dhania)\n- 2 tsp dried mango powder (amchur)\n\nOther Ingredients:\n- Whole wheat flour (gehun ka atta) for rolling\n- 12 tsp ghee for cooking\n\nFor Serving Aloo Paratha:\n- Curd\n\nAloo Paratha Dough:\n1. Combine whole wheat flour, ghee, and salt in a bowl; mix well.\n2. Add enough water and knead into a semi-stiff dough. Keep aside.\n\nAloo Paratha Stuffing:\n1. Heat ghee in a broad non-stick pan, add cumin seeds.\n2. Once seeds crackle, add onions and sauté for 1 to 2 minutes on medium flame.\n3. Add green chillies, mix well, and sauté for 1 minute.\n4. Add potatoes, salt, chilli powder, coriander, dry mango powder; mix well and cook for 1 to 2 minutes, stirring continuously.\n5. Divide the stuffing into 12 equal portions and set aside.\n\nHow to Make Aloo Paratha:\n1. Divide the dough into 12 equal portions and roll one portion into a 4\" diameter circle.\n2. Place a portion of stuffing in the center.\n3. Bring all sides together, seal tightly, and roll again into a 6\" diameter circle with a little flour.\n4. Heat a non-stick tava (griddle) and cook the paratha with 1 tsp of ghee until golden brown spots appear on both sides.\n5. Repeat with the remaining dough and stuffing to make 11 more aloo parathas.\n6. Serve the aloo parathas immediately with fresh curds."
    },    
    {
        "recipie_id": 110,
        "recipie_name": "Choco Lava Cake",
        "recipie_img": "https://img.freepik.com/free-photo/chocolate-pancakes-with-chocolate-syrup-banana_114579-3045.jpg?size=626&ext=jpg&ga=GA1.1.341020802.1702211776&semt=ais",
        "recipie_method": "For Wet Ingredients:\n- ½ cup Chilled Water\n- 3 tbsp Oil\n- 1 tsp Lemon juice\n- ⅓ cup Powdered sugar\n- 1 tsp Vanilla essence\n\nFor Dry Ingredients:\n- A pinch Salt\n- 2 heaped tbsp Cocoa powder\n- ½ cup Maida\n- ½ tsp Baking soda\n- 100 gm Dark chocolate\n\nFor Dusting Mould:\n- 1 tsp Butter\n- 2 tbsp Maida\n\nFor Wet Ingredients:\n- In a bowl, add chilled water, oil, lemon juice, powdered sugar, vanilla essence, and mix everything properly. Set it aside for further use.\n\nFor Dry Ingredients:\n- In another bowl, add salt, cocoa powder, maida, baking soda, and mix everything properly. Set it aside for further use.\n\nFor Dusting Mould:\n- Take any desired mould, apply butter to it, and keep it in the freezer to set the butter. Remove it and dust some maida on each side of the mould properly and again set it in the freezer until further use.\n\nFor Choco Lava Cake:\n- Now add the dry ingredients to wet ingredients and combine them properly but do not overmix it.\n- Once it’s mixed, remove the mould from the freezer and add 2-3 spoons of batter, then add a small cube of dark chocolate and again add 1-2 spoons of batter. Repeat this in all other moulds.\n- Keep the filled moulds in the freezer for a minute.\n- Remove and place in a hot steamer and steam it for 4-5 minutes, not more than that.\n- After that, remove the cake from the mould gently and serve warm."
    },    
    {
        "recipie_id": "111",
        "recipie_name": "Butter Chicken",
        "recipie_img": "https://img.freepik.com/free-photo/high-angle-chicken-meal_23-2148825122.jpg?size=626&ext=jpg&ga=GA1.1.341020802.1702211776&semt=ais",
        "recipie_method": "Ingredients:\n- 1 tablespoon oil\n- 1 tablespoon butter\n- 1 medium onion, diced\n- 1 teaspoon fresh ginger, finely minced or grated (or use paste)\n- 2-3 cloves garlic, finely minced or crushed\n- 1 ½ pounds about 2-3 boneless, skinless chicken breasts, cut into ¾-inch chunks\n- 4 tablespoons tomato paste, or 8 oz can of tomato sauce\n- 1 tablespoon garam masala\n- 1 teaspoon chili powder, or paprika, adjust to taste\n- 1 teaspoon Fenugreek, I use powder, but seeds or mustard seeds can be used too, optional*\n- 1 teaspoon cumin\n- 1 tsp salt\n- 1/4 tsp black pepper\n- 1 cup heavy cream, sub for half & half or yogurt for low fat\n- Hot cooked rice and naan for serving\n\nInstructions:\n- Heat a large skillet or medium saucepan over medium-high heat. Add the oil, butter, and onions and cook onions down until lightly golden, about 3-4 minutes.\n- Add ginger and garlic and let cook for 30 seconds, stirring so it doesn’t burn.\n- Add the chicken, tomato paste, and spices. Cook for 5-6 minutes or until everything is cooked through.\n- Add the heavy cream and simmer for 8-10 minutes stirring occasionally.\n- Serve over Basmati rice or with naan."
    },
    {
        "recipie_id": 112,
        "recipie_name": "Gajar Halwa",
        "recipie_img": "https://imgs.search.brave.com/aK75GyD6IAhn5QnCKsAruPPwu8NXpBFgVCDYZf0iAAg/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTI5/Mjg5NzM2MC9waG90/by9kZWxpY2lvdXMt/Z2FqYXIta2EtaGFs/d2Eta2VwdC1pbi1h/LXdoaXRlLWJvd2wu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PWdqQm9qRnpHNlFj/SGtFaTh1YXNuNVBp/MUNKenRDc3hfSnZ4/akZXRWtjOHM9",
        "recipie_method": "Ingredients:\n- Carrots - 600 grams\n- Malai - 1 cup\n- Sugar - ½ cup\n- Cashew - 2-3 teaspoons\n- Almonds - 2-3 teaspoons\n- Cardamom - 4, coarsely grounded\n\nProcess of making Gajar ka Halwa:\n- Put grated carrot and 1 cup fresh malai of homemade milk in the cooker. Burn the flame and mix the malai and carrot well. Close the cooker and cook on high flame till one whistle comes. After a whistle, cook it for 2 more minutes on low flame.\n- After the time is up, let the cooker cool down, then open it. A little milk must be separated from the malai, turn the flame on and cook on medium-high flame while stirring continuously till the milk gets mixed with carrots. When the milk is almost finished, then add 1 cup of sugar and cook till the sugar dissolves in halwa.\n- When the sugar dissolves well and halwa becomes thick, add 2-3 tsp cashews, 2-3 tsp almonds, and 4 coarsely crushed small cardamoms. Mix them well, turn off the flame, and take out the halwa. In this way, gajar ka halwa will be ready, serve it garnished with some cashew nuts and almonds and enjoy its taste."
    }   
]

